=== odafuta/K_COUNT_CLASSIFIER_TEST/acts_3.2/edu/uta/cse/fireeye/resources/fireeyeinput.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="System">
    <xs:complexType>
      <xs:all>
        <xs:element ref="Parameters"/>
        <xs:element minOccurs= "0" ref="Relations"/>
        <xs:element minOccurs= "0" ref="Testset"/>
        <xs:element minOccurs= "0" ref="Header"/>
        <xs:element minOccurs= "0" ref="Graph-Data"/>
        <xs:element minOccurs= "0" ref="Stat-Data"/>
        <xs:element minOccurs= "0" ref="Constraints"/>
      </xs:all>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Relations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded"  ref="Relation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Relation">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded"  ref="Parameter"/>
      </xs:sequence>
      <xs:attribute name="Strength" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Testset">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Testcase"/>
      </xs:sequence>
      <xs:attribute name="doi" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Testcase">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded"  minOccurs="0" ref="Value"/>
      </xs:sequence>
      <xs:attribute name="TCNo" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Header">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Graph-Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stat-Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ExecutionTime"/>
        <xs:element ref="MaxDomainSize"/>
        <xs:element ref="MinDomainSize"/>
        <xs:element ref="TotalNoOfCombination"/>
        <xs:element ref="TotalNoOfTests"/>
        <xs:element ref="Algorithm"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   <xs:element name="Constraints">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ExecutionTime"  type="xs:decimal"/>
  <xs:element name="MaxDomainSize"  type="xs:integer"/>
  <xs:element name="MinDomainSize"  type="xs:integer"/>
  <xs:element name="TotalNoOfCombination"  type="xs:integer"/>
  <xs:element name="TotalNoOfTests"  type="xs:integer"/>
  <xs:element name="Algorithm"  type="xs:NCName"/>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="values"/>
        <xs:element maxOccurs="unbounded" ref="value"/>
      </xs:choice>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="values">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded"  ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Value"  type="xs:string"/>
  <xs:element name="value" type="xs:NMTOKEN"/> 
</xs:schema>

=== odafuta/K_COUNT_CLASSIFIER_TEST/acts_3.2/edu/uta/cse/fireeye/resources/fireeyeinput.xml
<?xml version="1.0" encoding="UTF-8"?>
<System name="SampleSystem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\nbworkspace\fireeye\src\edu\uta\cse\fireeye\resources\fireeyeinput.xsd">
	<Parameters>
		<!-- only compare with MINSEP and MAXALTDIFF -->
		<Parameter name="Cur_Vertical_Sep">
			<values>
				<value>299</value>
				<value>300</value>
				<value>601</value>
			</values>
		</Parameter>
		<!-- only compare with MINSEP and MAXALTDIFF -->
		<Parameter name="Cur_Vertical_Sep">
			<values>
				<value>true</value>
				<value>false</value>
			</values>
		</Parameter>
		<!-- only compare with MINSEP and MAXALTDIFF -->
		<Parameter name="Two_of_Three_Reports_Valid">
			<values>
				<value>true</value>
				<value>false</value>
			</values>
		</Parameter>
		<!-- Low and High, only compare with Other_Tracked_Alt -->
		<Parameter name="Own_Tracked_Alt">
			<values>
				<value>1</value>
				<value>2</value>
			</values>
		</Parameter>
		<!-- Low and High, only compare with Other_Tracked_Alt -->
		<Parameter name="Other_Tracked_Alt">
			<values>
				<value>1</value>
				<value>2</value>
			</values>
		</Parameter>
		<!-- only compare with OLEV-->
		<Parameter name="Own_Tracked_Alt_Rate">
			<values>
				<value>600</value>
				<value>601</value>
			</values>
		</Parameter>
		<!-- only compare with OLEV -->
		<Parameter name="Alt_Layer_Value">
			<values>
				<value>0</value>
				<value>1</value>
				<value>2</value>
				<value>3</value>
			</values>
		</Parameter>
		<!-- compare with each other (also see NOZCROSS) and with ALIM -->
		<Parameter name="Up_Separation">
			<values>
				<value>0</value>
				<value>399</value>
				<value>400</value>
				<value>499</value>
				<value>500</value>
				<value>639</value>
				<value>640</value>
				<value>739</value>
				<value>740</value>
				<value>840</value>
			</values>
		</Parameter>
		<!-- compare with each other (also see NOZCROSS) and with ALIM -->
		<Parameter name="Down_Separation">
			<values>
				<value>0</value>
				<value>399</value>
				<value>400</value>
				<value>499</value>
				<value>500</value>
				<value>639</value>
				<value>640</value>
				<value>739</value>
				<value>740</value>
				<value>840</value>
			</values>
		</Parameter>
		<!-- compare with each other (also see NOZCROSS) and with ALIM -->
		<Parameter name="Other_RAC">
			<values>
				<value>NO_INTENT</value>
				<value>DO_NOT_CLIMB</value>
				<value>DO_NOT_DESCEND</value>
			</values>
		</Parameter>
		<!-- compare with each other (also see NOZCROSS) and with ALIM -->
		<Parameter name="Other_Capability">
			<values>
				<value>TCAS_TA</value>
				<value>OTHER</value>
			</values>
		</Parameter>
		<!-- compare with each other (also see NOZCROSS) and with ALIM -->
		<Parameter name="Climb_Inhibit">
			<values>
				<value>TRUE</value>
				<value>FALSE</value>
			</values>
		</Parameter>
	</Parameters>
	<Relation/>
	<Constraint/>
	<Misc/>
</System>
